# Generated by Django 2.1.5 on 2019-04-30 23:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHabits',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False)),
                ('HabitExercise', models.IntegerField(default=0)),
                ('HabitSleep', models.IntegerField(default=0, null=True)),
                ('HabitMood', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('HabitEnergy', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('HabitMeditate', models.BooleanField(default=False)),
                ('UserName', models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
