# Generated by Django 2.1.5 on 2019-05-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhabits',
            name='UserName',
        ),
    ]
