# Generated by Django 2.1.5 on 2019-05-03 17:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='habits',
            managers=[
                ('existing', django.db.models.manager.Manager()),
            ],
        ),
    ]
