# Generated by Django 2.1.5 on 2019-05-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTrackerApp', '0002_remove_userhabits_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhabits',
            name='UserID',
        ),
        migrations.AddField(
            model_name='userhabits',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
