# Generated by Django 2.1.5 on 2019-05-02 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTrackerApp', '0004_auto_20190501_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
