# Generated by Django 2.1.5 on 2019-05-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTrackerApp', '0005_auto_20190502_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habits',
            old_name='user',
            new_name='userID',
        ),
    ]
