# Generated by Django 2.1.5 on 2019-05-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTrackerApp', '0006_auto_20190502_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habits',
            old_name='userID',
            new_name='user',
        ),
    ]
