# Generated by Django 2.1.5 on 2019-05-02 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTrackerApp', '0007_auto_20190502_1047'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='habits',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='habits',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
