# Generated by Django 2.1.5 on 2019-05-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTrackerApp', '0008_auto_20190502_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
