# Generated by Django 2.1.5 on 2019-05-02 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTrackerApp', '0009_auto_20190502_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
