# Generated by Django 2.1.5 on 2019-05-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTrackerApp', '0010_auto_20190502_1301'),
    ]

    operations = [
    ]
