# Generated by Django 2.1.5 on 2019-05-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTrackerApp', '0011_merge_20190503_1147'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='habits',
            managers=[
            ],
        ),
    ]
