# Generated by Django 2.1.5 on 2019-05-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTrackerApp', '0012_auto_20190509_1616'),
        ('HabitTrackerApp', '0012_auto_20190509_1502'),
    ]

    operations = [
    ]
