# Generated by Django 2.1.5 on 2019-05-15 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTrackerApp', '0013_merge_20190513_1536'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='habits',
            managers=[
            ],
        ),
    ]
