# Generated by Django 2.1.5 on 2019-05-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HabitTrackerApp', '0013_merge_20190513_1246'),
        ('HabitTrackerApp', '0013_merge_20190513_1358'),
        ('HabitTrackerApp', '0013_merge_20190514_1713'),
        ('HabitTrackerApp', '0013_merge_20190515_1137'),
        ('HabitTrackerApp', '0014_auto_20190515_1524'),
    ]

    operations = [
    ]
