from django import forms


class CurrencyForm(forms.Form):
    original = forms.CharField(required=False)
    amount = forms.CharField(required=False)
    currency = forms.CharField(required=False)
    base = forms.CharField(required=False)
    money = forms.FloatField()
    base_currency = forms.ChoiceField(choices=[
        ('USD', 'USD (US$)'),
        ('EUR', 'EUR (€)'), 
        ('BTC', 'BTC (₿)'),
        ('JPY', 'JPY (¥)'),
        ('GBP', 'GBP (£)'),
        ('AUD', 'AUD (A$)'),
        ('CAD', 'CAD (C$)'),
        ('CHF', 'CHF (Fr)'),
        ('CNY', 'CNY (元)'),
        ('SEK', 'SEK (kr)'),
        ('NZD', 'NZD (NZ$)'),
        ('MXN', 'MXN ($)'),
        ('SGD', 'SGD (S$)'),
        ('HKD', 'HKD (HK$)'),
        ('NOK', 'NOK (kr)'),
        ('KRW', 'KRW (₩)'),
        ('TRY', 'TRY (₺)'),
        ('RUB', 'RUB (₽)'),
        ('INR', 'INR (₹)'),
        ('BRL', 'BRL (R$)'),
        ('ZAR', 'ZAR (R)')])
    target_currency = forms.ChoiceField(choices=[
        ('EUR', 'EUR (€)'), 
        ('USD', 'USD (US$)'),
        ('BTC', 'BTC (₿)'),
        ('JPY', 'JPY (¥)'),
        ('GBP', 'GBP (£)'),
        ('AUD', 'AUD (A$)'),
        ('CAD', 'CAD (C$)'),
        ('CHF', 'CHF (Fr)'),
        ('CNY', 'CNY (元)'),
        ('SEK', 'SEK (kr)'),
        ('NZD', 'NZD (NZ$)'),
        ('MXN', 'MXN ($)'),
        ('SGD', 'SGD (S$)'),
        ('HKD', 'HKD (HK$)'),
        ('NOK', 'NOK (kr)'),
        ('KRW', 'KRW (₩)'),
        ('TRY', 'TRY (₺)'),
        ('RUB', 'RUB (₽)'),
        ('INR', 'INR (₹)'),
        ('BRL', 'BRL (R$)'),
        ('ZAR', 'ZAR (R)')])