# Generated by Django 2.1.5 on 2019-04-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('radius', models.CharField(max_length=5)),
                ('postal', models.CharField(max_length=5)),
            ],
        ),
    ]
