# Generated by Django 2.1.5 on 2019-05-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficApp', '0002_auto_20190513_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='end',
            field=models.CharField(max_length=175),
        ),
        migrations.AlterField(
            model_name='route',
            name='start',
            field=models.CharField(max_length=175),
        ),
    ]
