# Generated by Django 2.1.5 on 2019-05-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PodcastsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(choices=[('Society & Culture', 'Society & Culture'), ('News & Politics', 'News & Politics'), ('Science & Medicine', 'Science & Medicine'), ('Sports', 'Sports'), ('Comedy', 'Comedy'), ('Pop Culture, TV & Film', 'Pop Culture, TV & Film'), ('Education', 'Education'), ('Kids & Family', 'Kids & Family'), ('Storytelling', 'Storytelling'), ('Technology', 'Technology'), ('Music & Commentary', 'Music & Commentary'), ('Everything', 'Everything'), ('Religion & Spirituality', 'Religion & Spirituality'), ('Games & Hobbies', 'Games & Hobbies'), ('Business', 'Business'), ('Lifestyle & Health', 'Lifestyle & Health')], max_length=60),
        ),
    ]
