# Generated by Django 2.1.5 on 2019-05-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PodcastsApp', '0002_auto_20190521_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(choices=[('Society & Culture', 'Society & Culture'), ('Comedy', 'Comedy'), ('Sports', 'Sports'), ('Business', 'Business'), ('Games & Hobbies', 'Games & Hobbies'), ('Storytelling', 'Storytelling'), ('News & Politics', 'News & Politics'), ('Technology', 'Technology'), ('Everything', 'Everything'), ('Lifestyle & Health', 'Lifestyle & Health'), ('Religion & Spirituality', 'Religion & Spirituality'), ('Kids & Family', 'Kids & Family'), ('Music & Commentary', 'Music & Commentary'), ('Science & Medicine', 'Science & Medicine'), ('Pop Culture, TV & Film', 'Pop Culture, TV & Film'), ('Education', 'Education')], max_length=60),
        ),
    ]
