# Generated by Django 2.1.5 on 2019-05-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PodcastsApp', '0003_auto_20190522_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(choices=[('Society & Culture', 'Society & Culture'), ('Pop Culture, TV & Film', 'Pop Culture, TV & Film'), ('Education', 'Education'), ('Games & Hobbies', 'Games & Hobbies'), ('Comedy', 'Comedy'), ('Storytelling', 'Storytelling'), ('Kids & Family', 'Kids & Family'), ('Everything', 'Everything'), ('Science & Medicine', 'Science & Medicine'), ('Lifestyle & Health', 'Lifestyle & Health'), ('Sports', 'Sports'), ('Religion & Spirituality', 'Religion & Spirituality'), ('Music & Commentary', 'Music & Commentary'), ('Technology', 'Technology'), ('Business', 'Business'), ('News & Politics', 'News & Politics')], max_length=60),
        ),
    ]
