# Generated by Django 2.1.5 on 2019-05-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PodcastsApp', '0006_auto_20190522_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(choices=[('Business', 'Business'), ('News & Politics', 'News & Politics'), ('Sports', 'Sports'), ('Pop Culture, TV & Film', 'Pop Culture, TV & Film'), ('Education', 'Education'), ('Technology', 'Technology'), ('Music & Commentary', 'Music & Commentary'), ('Everything', 'Everything'), ('Lifestyle & Health', 'Lifestyle & Health'), ('Society & Culture', 'Society & Culture'), ('Kids & Family', 'Kids & Family'), ('Religion & Spirituality', 'Religion & Spirituality'), ('Comedy', 'Comedy'), ('Games & Hobbies', 'Games & Hobbies'), ('Science & Medicine', 'Science & Medicine'), ('Storytelling', 'Storytelling')], max_length=60),
        ),
    ]
