# Generated by Django 2.1.5 on 2019-05-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PodcastsApp', '0008_auto_20190523_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(choices=[('Science & Medicine', 'Science & Medicine'), ('Games & Hobbies', 'Games & Hobbies'), ('Sports', 'Sports'), ('Business', 'Business'), ('Comedy', 'Comedy'), ('Storytelling', 'Storytelling'), ('Education', 'Education'), ('Religion & Spirituality', 'Religion & Spirituality'), ('Society & Culture', 'Society & Culture'), ('Technology', 'Technology'), ('Lifestyle & Health', 'Lifestyle & Health'), ('Kids & Family', 'Kids & Family'), ('News & Politics', 'News & Politics'), ('Pop Culture, TV & Film', 'Pop Culture, TV & Film'), ('Everything', 'Everything'), ('Music & Commentary', 'Music & Commentary')], max_length=60),
        ),
    ]
