# Generated by Django 2.1.5 on 2019-05-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PodcastsApp', '0009_auto_20190523_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
