# Generated by Django 2.1.5 on 2019-04-24 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AccountsApp', '0003_auto_20190414_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('budget_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('budget_target', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountsApp.UserProfile')),
            ],
        ),
    ]
