# Generated by Django 2.1.5 on 2019-04-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
    ]
