# Generated by Django 2.1.5 on 2019-04-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetApp', '0002_remove_budget_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='budget_target',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='budget_value',
            new_name='target',
        ),
    ]
