# Generated by Django 2.1.5 on 2019-04-25 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetApp', '0003_auto_20190424_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='balance',
            new_name='actual',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='target',
            new_name='budget',
        ),
    ]
