# Generated by Django 2.1.5 on 2019-04-30 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0003_auto_20190414_1625'),
        ('BudgetApp', '0005_auto_20190429_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AccountsApp.UserProfile'),
            preserve_default=False,
        ),
    ]
