# Generated by Django 2.1.5 on 2019-05-09 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BandsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bands',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
