# Generated by Django 2.1.5 on 2019-05-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
