# Generated by Django 2.1.5 on 2019-05-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataApp', '0002_auto_20190514_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='index',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
        migrations.AddField(
            model_name='movie',
            name='display',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='sort',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
