# Generated by Django 2.1.5 on 2019-05-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataApp', '0003_auto_20190516_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('display', models.IntegerField(default=5, null=True)),
                ('sort', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='display',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='sort',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='user_id',
        ),
    ]
