# Generated by Django 2.1.5 on 2019-05-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataApp', '0004_auto_20190516_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviepreferences',
            old_name='sort',
            new_name='sort_type',
        ),
    ]
