# Generated by Django 2.1.5 on 2019-05-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataApp', '0006_auto_20190516_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepreferences',
            name='genre_sort',
            field=models.CharField(default='All', max_length=20, null=True),
        ),
    ]
