# Generated by Django 2.1.7 on 2019-04-01 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessagesApp', '0004_auto_20190401_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
