# Generated by Django 2.1.5 on 2019-05-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessagesApp', '0006_auto_20190408_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.IntegerField(null=True),
        ),
    ]
