# Generated by Django 2.1.5 on 2019-05-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessagesApp', '0007_message_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
