# Generated by Django 2.1.5 on 2019-05-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessagesApp', '0008_auto_20190514_1713'),
        ('MessagesApp', '0008_auto_20190515_1322'),
    ]

    operations = [
    ]
