# Generated by Django 2.1.5 on 2019-04-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0003_auto_20190414_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lat',
            field=models.DecimalField(decimal_places=4, default=122.6793, max_digits=9),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lng',
            field=models.DecimalField(decimal_places=4, default=45.5155, max_digits=9),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
