# Generated by Django 2.1.5 on 2019-04-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zip',
            name='name',
        ),
        migrations.AddField(
            model_name='zip',
            name='zip',
            field=models.CharField(default='', max_length=5),
        ),
    ]
