# Generated by Django 2.1.5 on 2019-06-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0003_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=50)),
                ('current_temp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
                ('current_humidity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
                ('weather_description', models.CharField(default='', max_length=50)),
                ('weather_icon', models.CharField(default='', max_length=50)),
                ('high_temp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
                ('low_temp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
                ('wind_speed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='city',
        ),
        migrations.RemoveField(
            model_name='zip',
            name='zip',
        ),
        migrations.AddField(
            model_name='city',
            name='zip',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='zip',
            name='city',
            field=models.CharField(default='UserProfile.city', max_length=50),
        ),
    ]
