# Generated by Django 2.1.5 on 2019-06-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0006_auto_20190606_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='zip',
            name='zip',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
